// <auto-generated />
namespace Projet_Commerce_Electronique.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class thirddd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(thirddd));
        
        string IMigrationMetadata.Id
        {
            get { return "202504051445050_thirddd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
